version: '3'
services:
  drugstore_api: 
    deploy:
      replicas: 3 
    image: aco99/drugstore_api
    environment:
      SFTP_IP: sftp-server
      SFTP_USERNAME: user
      SFTP_PASSWORD: password
      DRUGSTORE_GRPC_DOMAIN: drugstore_api
      RABBIT_HOST: message-broker
      DBServer: postgres-server-drugstore
      DBPerver: 5433
      DBUser: postgres
      DBPassword: 123
      DB: drugstore
    restart: on-failure
    ports:
      - "8082:80"    