version: '3'
services:
  postgres-server-hospital:
    image: postgres
    deploy:
      replicas: 2
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: hospital
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
  
  hospital_api:
    depends_on:
      - postgres-server-hospital
    image: aco99/hospital_api
    deploy:
      replicas: 3
    environment:
      DBServer: postgres-server-hospital
      DBPort: 5432
      DBUser: postgres
      DBPassword: 123
      DB: hospital
    ports:
      - "8081:80"
      - "4112:4111"    
  patient_client:
    deploy:
      replicas: 3
    links:
      - hospital_api
    #build: ../PatientApp/Frontend/PatientApp
    image: aco99/patient_client
    ports:
      - "4201:80"