// <auto-generated />
using System;
using Hospital.PatientEvent.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Hospital.Migrations.EventDb
{
    [DbContext(typeof(EventDbContext))]
    [Migration("20220110204026_NewMigrationEvent")]
    partial class NewMigrationEvent
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Hospital.PatientEvent.Model.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("EventName")
                        .HasColumnType("text");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("PatientEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventName = "Klik",
                            EventTime = new DateTime(2022, 1, 10, 21, 40, 24, 376, DateTimeKind.Local).AddTicks(4792)
                        },
                        new
                        {
                            Id = 2,
                            EventName = "Klik",
                            EventTime = new DateTime(2022, 1, 10, 21, 40, 24, 382, DateTimeKind.Local).AddTicks(1956)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
