version: '3'
services:
  postgres-server:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: hospital
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
      
  integration_api:
    depends_on:
      - sftp-server
      - message-broker   
      - hospital_api
    build:
      context: .
      args:
        SFTP_IP: sftp-server
        SFTP_USERNAME: user
        SFTP_PASSWORD: password
        RABBIT_HOST: message-broker
        HOSPITAL_GRPC_DOMAIN: hospital_api
        HOSPITAL_GRPC_PORT: 8081
        DRUGSTORE_GRPC_DOMAIN: drugstore_api
        DRUGSTORE_GRPC_PORT: 8082
    image: aco99/integration_api
    environment:
      DBServer: postgres-server-hospital
      DBPort: 5432
      DBUser: postgres
      DBPassword: 123
      DB: hospital
      RABBIT_HOST: message-broker
    restart: always
    ports:
      - "8083:80"

  manager_client:
   build: ../ManagerAngularApp/ManagerAngularApp
   image: aco99/manager_client
   ports:
    - "4203:80" 