version: '2.2'
services:
  postgres-server-hospital:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: hospital
      POSTGRES_USER: postgres
    ports:
      - "5434:5432"
  hospital_api:
     depends_on:
       - postgres-server-hospital
     image: aco99/hospital_api
     healthcheck:
       test: ["CMD", "curl", "-f", "http://localhost"]
       interval: 1m30s
       timeout: 15s
       retries: 5
     environment:
       DBServer: postgres-server-hospital
       DBPort: 5432
       DBUser: postgres
       DBPassword: 123
       DB: hospital
     restart: always
     ports:
       - "8081:80"
  patient_client:
    image: aco99/patient_client
    ports:
      - "4201:80"

  selenium:
      image: selenium/standalone-chrome:96.0.4664.45
      ports:
        - "4444:4444"

  e2e-test:
    environment:
      MF_HOST: "http://patient_client"
    build:
      context: ../../HospitalAPI/HospitalAPI
      dockerfile: E2ETests.Dockerfile
      args:
        MF_HOST: "http://patient_client"
    entrypoint: dotnet test
    restart: always
    depends_on:
      hospital_api:
        condition: service_healthy
      patient_client:
        condition: service_started
      selenium:
        condition: service_started
    links:
      - selenium