version: '3'
services:
  postgres-server-drugstore:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: drugstore
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"

  postgres-server-hospital:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: hospital
      POSTGRES_USER: postgres
    ports:
      - "5434:5432"

  message-broker:
    image: rabbitmq:management-alpine
    ports:
      - 15672:15672

  sftp-server:
    image: atmoz/sftp
    ports:
      - "23:22"
    volumes:
      - /upload/DrugstoreFiles:/home/user/upload/DrugstoreFiles
      - /upload/HospitalFiles:/home/user/upload/HospitalFiles
    command: user:password:1001

  integration_api:
    depends_on:
      - sftp-server
      - message-broker
    #build: ../../IntegrationApp/
    image: aco99/integration_api

    environment:
      DBServer: postgres-server-hospital
      DBPort: 5432
      DBUser: postgres
      DBPassword: 123
      DB: hospital
      SFTP_IP: sftp-server
      SFTP_USERNAME: user
      SFTP_PASSWORD: password
      RABBIT_HOST: message-broker
      HOSPITAL_GRPC_DOMAIN: hospital_api
      HOSPITAL_GRPC_PORT: 8081
      DRUGSTORE_GRPC_DOMAIN: drugstore_api
      DRUGSTORE_GRPC_PORT: 8082
    restart: always
    ports:
      - "8083:80"

  drugstore_api:
    depends_on:
      - postgres-server-drugstore
      - message-broker
      - sftp-server
    #build: ../../DrugstoreApp/Backend/DrugstoreAPI
    image: aco99/drugstore_api
    environment:
      SFTP_IP: sftp-server
      SFTP_USERNAME: user
      SFTP_PASSWORD: password
      DBServer: postgres-server-drugstore
      RABBIT_HOST: message-broker
      DBUser: postgres
      DBPassword: 123
      DB: drugstore
    restart: always
    ports:
      - "8082:80"

  manager_client:
   build: ../../ManagerAngularApp/ManagerAngularApp
   image: aco99/manager_client
   ports:
    - "4203:80"

  selenium:
      image: selenium/standalone-chrome:96.0.4664.45
      ports:
        - "4444:4444"

  integration-e2e-test:
    container_name: integration-e2e-test
    environment:
      MF_HOST: "http://manager_client"
    build:
      context: ../../IntegrationApp
      dockerfile: E2E.Dockerfile
      args:
        MF_HOST: "http://manager_client"
    entrypoint: dotnet test
    restart: always
    depends_on:
      - integration_api
      - manager_client
      - selenium
    links:
      - selenium
  hospital-e2e-test:
    container_name: hospital-e2e-test
    environment:
      MF_HOST: "http://manager_client"
      PF_HOST: "http://patient_client"
    build:
      context: ../../HospitalAPI/HospitalAPI
      dockerfile: E2ETests.Dockerfile
      args:
        MF_HOST: "http://manager_client"
        PF_HOST: "http://patient_client"
    entrypoint: dotnet test
    restart: always
    depends_on:
      - hospital_api
      - patient_client
      - selenium
    links:
      - selenium