version: '3'
services:
  postgres-server-drugstore:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: drugstore
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
  
  postgres-server-hospital:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: hospital
      POSTGRES_USER: postgres
    ports:
      - "5434:5432"

  message-broker:
    image: rabbitmq:management-alpine
    container_name: rabbitmq-broker
    ports:
      - 15672:15672

  sftp-server:
    image: atmoz/sftp
    ports:
      - "23:22"
    volumes:
      - /upload/DrugstoreFiles:/home/user/upload/DrugstoreFiles
      - /upload/HospitalFiles:/home/user/upload/HospitalFiles
    command: user:password:1001

  integration_api:
    depends_on:
      - sftp-server
      - message-broker   
    #build: ../../IntegrationApp/
    image: aco99/integration_api
    healthcheck:
      test: ["CMD", "curl", "http://localhost/","||","exit","1"]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 15s
    environment:
      DBServer: postgres-server-hospital
      DBPort: 5432
      DBUser: postgres
      DBPassword: 123
      DB: hospital
      SFTP_IP: sftp-server
      SFTP_USERNAME: user
      SFTP_PASSWORD: password
      RABBIT_HOST: message-broker
      HOSPITAL_GRPC_DOMAIN: hospital_api
      HOSPITAL_GRPC_PORT: 8081
      DRUGSTORE_GRPC_DOMAIN: drugstore_api
      DRUGSTORE_GRPC_PORT: 8082
    restart: always
    ports:
      - "8083:80"  

  drugstore_api:
    depends_on:  
      - postgres-server-drugstore
      - message-broker
      - sftp-server
    #build: ../../DrugstoreApp/Backend/DrugstoreAPI
    healthcheck:
      test: ["CMD", "curl", "http://localhost/","||","exit","1"]
      interval: 15s
      timeout: 30s
      retries: 15
      start_period: 15s
    image: aco99/drugstore_api
    environment:
      SFTP_IP: sftp-server
      SFTP_USERNAME: user
      SFTP_PASSWORD: password
      DBServer: postgres-server-drugstore
      RABBIT_HOST: message-broker
      DBUser: postgres
      DBPassword: 123
      DB: drugstore
    restart: always
    ports:
      - "8082:80" 

  manager_client:
   build: ../../ManagerAngularApp/ManagerAngularApp
   image: aco99/manager_client
   ports:
    - "4203:80"
  
  selenium-hub:
    image: selenium/hub:4.1.1-20211217
    container_name: selenium-hub
    ports: 
      - "4444:4444"
      - "4443:4443"
      - "4442:4442"
 
  chrome:
    depends_on:
      - selenium-hub
    image: selenium/node-chrome:4.1.1-20211217
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      
  integration-e2e-test:
    environment:
      MF_HOST: "http://manager_client"
    build:
      context: ../../IntegrationApp
      dockerfile: E2E.Dockerfile
      args: 
        MF_HOST: "http://manager_client"
    entrypoint: dotnet 
    restart: always
    depends_on:
      integration_api:
        condition: service_healthy
      manager_client:
        condition: service_started
      chrome:
        condition: service_started
    links:
      - chrome

  
      
