version: '3'
services:
  postgres-server-drugstore:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: drugstore
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
  
  postgres-server-hospital:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: hospital
      POSTGRES_USER: postgres
    ports:
      - "5434:5432"

  message-broker:
    image: rabbitmq:management-alpine
    container_name: rabbitmq-broker
    ports:
      - 15672:15672

  sftp-server:
    image: atmoz/sftp
    ports:
      - "23:22"
    volumes:
      - /upload/DrugstoreFiles:/home/user/upload/DrugstoreFiles
      - /upload/HospitalFiles:/home/user/upload/HospitalFiles
    command: user:password:1001

  hospital_api:
     depends_on:
       - postgres-server-hospital
     build: ../../
     healthcheck:
      test: ["CMD", "curl", "http://localhost/","||","exit","1"]
      interval: 15s
      timeout: 30s
      retries: 25
      start_period: 15s
     image: aco99/hospital_api
     environment:
       DBServer: postgres-server-hospital
       DBPort: 5432
       DBUser: postgres
       DBPassword: 123
       DB: hospital
     restart: always
     ports:
       - "8081:80"

  integration_api:
    depends_on:
      - sftp-server
      - message-broker   
      - hospital_api
    build: ../../IntegrationApp/
    image: aco99/integration_api
    healthcheck:
      test: ["CMD", "curl", "http://localhost/","||","exit","1"]
      interval: 15s
      timeout: 30s
      retries: 25
      start_period: 15s
    environment:
      DBServer: postgres-server-hospital
      DBPort: 5432
      DBUser: postgres
      DBPassword: 123
      DB: hospital
      SFTP_IP: sftp-server
      SFTP_USERNAME: user
      SFTP_PASSWORD: password
      RABBIT_HOST: message-broker
      HOSPITAL_GRPC_DOMAIN: hospital_api
      HOSPITAL_GRPC_PORT: 8081
      DRUGSTORE_GRPC_DOMAIN: drugstore_api
      DRUGSTORE_GRPC_PORT: 8082
    restart: always
    ports:
      - "8083:80"  
  
  drugstore_api:
    depends_on:  
      - postgres-server-drugstore
      - message-broker
      - sftp-server
    build: ../../DrugstoreApp/Backend/DrugstoreAPI
    healthcheck:
      test: ["CMD", "curl", "http://localhost/","||","exit","1"]
      interval: 15s
      timeout: 30s
      retries: 25
      start_period: 15s
    image: aco99/drugstore_api
    environment:
      SFTP_IP: sftp-server
      SFTP_USERNAME: user
      SFTP_PASSWORD: password
      DBServer: postgres-server-drugstore
      RABBIT_HOST: message-broker
      DBUser: postgres
      DBPassword: 123
      DB: drugstore
    restart: always
    ports:
      - "8082:80" 
  drugstore_test:
      build:
        context: ../../DrugstoreApp/Backend/DrugstoreAPI
        dockerfile: IntegrationTestDockerfile
        args:
          DBUser: postgres
          DBServer: postgres-server-drugstore
          DBTest: drugstore
          DBPassword: 123
      entrypoint: dotnet test --filter Type=IntegrationTest --no-restore
      depends_on:
        drugstore_api:
          condition: service_healthy
  hospital_test:
    build:
      context: ../..
      dockerfile: IntegrationTestHospital.Dockerfile
      args:
        DBServer: postgres-server-hospital
        DBUser: postgres
        DBTest: hospital
        DBPassword: 123
    entrypoint: dotnet test --filter Type=IntegrationTest --no-restore
    depends_on:
      hospital_api:
        condition: service_healthy
  integration_test:
    build:
      context: ../../IntegrationApp
      dockerfile: IntegrationTest.Dockerfile
      args:
        DBServer: postgres-server-hospital
        DBUser: postgres
        DBTest: hospital
        DBPassword: 123
    entrypoint: dotnet test --filter Type=IntegrationTest --no-restore
    depends_on:
      integration_api:
        condition: service_healthy      
  
      
