// <auto-generated />
using System;
using Integration.IntegrationEvents.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Integration.Migrations.EventDb
{
    [DbContext(typeof(EventDbContext))]
    partial class EventDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Integration.IntegrationEvents.Model.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("EventName")
                        .HasColumnType("text");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("IntegrationEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventName = "Klik",
                            EventTime = new DateTime(2022, 1, 10, 21, 1, 29, 817, DateTimeKind.Local).AddTicks(9973)
                        },
                        new
                        {
                            Id = 2,
                            EventName = "Klik",
                            EventTime = new DateTime(2022, 1, 10, 21, 1, 29, 824, DateTimeKind.Local).AddTicks(2984)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
