// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model.DataBaseContext;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Integration.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20211106011911_DrugstoreMigration")]
    partial class DrugstoreMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Integration.Model.Drugstore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("ApiKey")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Drugstores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Kneza 22",
                            ApiKey = "aaabbbccc",
                            Email = "apoteka1@gmail.com",
                            Name = "Apoteka prva",
                            Url = "www.apoteka.rs"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Kneza 23",
                            ApiKey = "111222333",
                            Email = "apoteka2@gmail.com",
                            Name = "Apoteka druga",
                            Url = "www.apotekica.rs"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Kneza 265",
                            ApiKey = "555333",
                            Email = "apoteka3@gmail.com",
                            Name = "Apoteka treca",
                            Url = "www.apotekcina.rs"
                        });
                });

            modelBuilder.Entity("Integration.Model.DrugstoreFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int>("DrugstoreId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecievedTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Response")
                        .HasColumnType("text");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("DrugstoreFeedbacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Nije mi se svidela usluga",
                            DrugstoreId = 1,
                            RecievedTime = new DateTime(2021, 11, 6, 2, 19, 10, 686, DateTimeKind.Local).AddTicks(7991),
                            Response = "Nemoj da lazes!",
                            SentTime = new DateTime(2021, 11, 6, 2, 19, 10, 689, DateTimeKind.Local).AddTicks(8405)
                        },
                        new
                        {
                            Id = 2,
                            Content = "Svidjela usluga",
                            DrugstoreId = 2,
                            RecievedTime = new DateTime(2021, 11, 6, 2, 19, 10, 689, DateTimeKind.Local).AddTicks(9143),
                            Response = "Nemoj da lazes!",
                            SentTime = new DateTime(2021, 11, 6, 2, 19, 10, 689, DateTimeKind.Local).AddTicks(9188)
                        },
                        new
                        {
                            Id = 3,
                            Content = "Nije mi se svidela usluga",
                            DrugstoreId = 3,
                            RecievedTime = new DateTime(2021, 11, 6, 2, 19, 10, 689, DateTimeKind.Local).AddTicks(9201),
                            Response = "Nemoj da lazes!",
                            SentTime = new DateTime(2021, 11, 6, 2, 19, 10, 689, DateTimeKind.Local).AddTicks(9204)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
