version: '3'
services:
    selenium:
      image: selenium/standalone-chrome:96.0.4664.45
      ports:
        - "4444:4444"
    patient_client:
       image: aco99/patient_client
       ports:
         - "4200:80"