name: CD
on:
  push:
    branches: [ development ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Execute SSH commmands on remote server
        uses: ian-whitestone/action-ssh@master
        with:
          hosts: 'student@79.101.34.218'
          port: 22212
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          command: |
            echo "Connected"
            docker kill $(docker ps -q)
            cd PSV
            git checkout master
            git pull origin master
            cd src/IntegrationApp
            docker-compose build
            docker-compose up -d
            docker push aco99/gateway
            docker push aco99/hospital_api
            docker push aco99/integration_api
            docker push aco99/drugstore_api
            docker push aco99/patient_client
            docker push aco99/drugstore_client
            docker push aco99/manager_client
            
