name: CD
on:
  push:
    branches: [ development ]
    
jobs:
  deploy-build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server and build
        uses: ian-whitestone/action-ssh@master
        with:
          hosts: 'student@79.101.34.218'
          port: 22212
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          command: |
            echo "Connected"
            docker kill $(docker ps -q)
            cd PSV
            git checkout development
            git pull origin development
            cd src/IntegrationApp
            docker-compose build
  test-e2e-integration:
    needs: deploy-build
    runs-on: ubuntu-latest
    steps:
      - name: Run E2E Tests for Integration Project
        uses: ian-whitestone/action-ssh@master
        with:
          hosts: 'student@79.101.34.218'
          port: 22212
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          command: |
            echo "Connection successful!"
            cd PSV/src/config/testing
            docker-compose -f e2e-integration-test-docker-compose.yml up --exit-code-from integration-e2e-test integration-e2e-test
  
  test-e2e-hospital:
    needs: [deploy-build, test-e2e-integration]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Run E2E Tests for Hospital Project
        uses: ian-whitestone/action-ssh@master
        with:
          hosts: 'student@79.101.34.218'
          port: 22212
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          command: |
            echo "Connection successful!"
            cd PSV/src/config/testing
            docker-compose -f e2e-integration-test-docker-compose.yml up --exit-code-from hospital-e2e-test hospital-e2e-test
  
  kill-docker-containers:
      needs: [deploy-build, test-e2e-integration, test-e2e-hospital]
      if: ${{ always() }}
      runs-on: ubuntu-latest
      steps:
        - name: Run E2E Tests for Hospital Project
          uses: ian-whitestone/action-ssh@master
          with:
            hosts: 'student@79.101.34.218'
            port: 22212
            privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
            debug: true
            command: |
              echo "Connection successful!"  
              docker kill $(docker ps -q)

  deploy-to-docker-hub-run:
    runs-on: ubuntu-latest
    needs: [kill-docker-containers]
    if: ${{ always() }}
    steps:
      - name: Deploy to server and build
        uses: ian-whitestone/action-ssh@master
        with:
          hosts: 'student@79.101.34.218'
          port: 22212
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          command: |
            echo "Connected"
            docker-compose up -d
            docker push aco99/gateway
            docker push aco99/hospital_api
            docker push aco99/integration_api
            docker push aco99/drugstore_api
            docker push aco99/patient_client
            docker push aco99/drugstore_client
            docker push aco99/manager_client
            
