name: HospitalIntegrationTests

on:
  push: 
    branches: [ development, feat ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/DrugstoreApp/Backend/DrugstoreAPI/IntegrationTestDockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/integration_test_drugstore:latest