name: DrugstoreUnitTests

on:
  push:
    paths: 
      - "src/DrugstoreApp/**"
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        working-directory: src/DrugstoreApp/Backend/DrugstoreAPI
        run: dotnet restore 
      - name: Build
        working-directory: src/DrugstoreApp/Backend/DrugstoreAPI
        run: dotnet build --configuration Release --no-restore
      - name: Test
        working-directory: src/DrugstoreApp/Backend/DrugstoreAPI
        run: dotnet test --filter Type=UnitTest --no-restore