name: HospitalIntegrationTests

on:
  push: 
    branches: [ development, fix#6run_integraton_tests ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/DrugstoreApp/Backend/DrugstoreAPI/IntegrationTestDockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/integration_test_drugstore:latest