name: Run E2E Test on server
on:
  push:
    branches: [ development, fix-integration-testing ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Execute SSH commmands on remote server
        uses: ian-whitestone/action-ssh@master
        with:
          hosts: 'student@79.101.34.218'
          port: 22212
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          command: |
            echo "Connection successful!"
            docker kill $(docker ps -q)
            git pull origin fix-integration-testing
            cd PSV/src
            cd config/testing
            docker-compose -f e2e-hospital-docker-compose.yml up --exit-code-from integration-e2e-test
            
