name: DrugstoreIntegrationTest
on:
  push:
    branches: [ development ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Execute SSH commmands on remote server
        uses: ian-whitestone/action-ssh@master
        with:
          hosts: 'student@79.101.34.218'
          port: 22212
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          command: |
            echo "Connection successful!"
            docker kill $(docker ps -q)
            cd PSV
            git checkout development
            git pull origin development
            cd config/testing
            docker-compose -f e2e-integration-test-docker-compose.yml up --exit-code-from integration-e2e-test
            
