name: IntegrationUnitTests

on:
  pull_request: 
    branches: [ development ]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '3.1.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore src/\"Integration API\"/IntegrationAPI.sln
      - name: Build
        run: dotnet build src/\"Integration API\"/IntegrationAPI.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test src/\"Integration API\"/IntegrationAPI.sln --filter Type=UnitTest --no-restore --verbosity normal
