name: Integration tests
on:
  pull_request: 
    branches: [ development ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: RunTests
        run: docker-compose -f src/config/testing/integration-test-docker-compose.yml build 
      