name: Block Repository Write

on:
  schedule:
    - cron: "*/5 * * * *"
    - cron: "0 4 7,21 11 *"
    - cron: "0 4 5,19 12 *"
    - cron: "0 4 2,16,30 1 *"


jobs:
  run-prevent:
    runs-on: ubuntu-latest
    steps:
      - name: Test 
        run: $PAT_GITHUB
      - name: Send request
        run: |
          curl \ -X PUT \ -H "Accept: application/vnd.github.v3+json" \ 
          -H "Authorization: token $PAT_GITHUB" \ https://api.github.com/orgs/danijelr/teams/developers/repos/danijelr/tmp \ 
          -d '{"permission":"pull"}'