name: Block Developers Write

on:
  schedule:
    - cron: "0 3 27 11 *"
    - cron: "0 3 3,17,31 12 *"
    - cron: "0 4 14,28 1 *"


jobs:
  run-prevent:
    runs-on: ubuntu-latest
    steps:
      - name: Send request
        run: |
          curl -i -u Aleksandar999:${{ secrets.PAT_GITHUB }} https://api.github.com/orgs/PSV-2021/teams/developers/repos/PSV-2021/PSV -X PUT -d '{"permission":"pull"}' -H "Accept:application/vnd.github.v3+json"
